language: node_js
node_js:
- '6'
script:
- npm run compile
- npm run coverage
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: deblock.thomas.62@gmail.com
  api_key:
    secure: G9njE7WMo/J2NZMOm/sCWKVfc5zPcFgllfrHfnZ4Fp8m7pZ4A8QULzvMijUHqueImK4+2hyZ6P85cjcydRypx8R1+l0Du3vttpvnx52xZvwRbuFSgvGTJbxHJga9afEXsrqKVea8Dq4z8F09cfGdh5twWZBCTuUtfuFLAweiOYgq4NzYJtCPn3tz6k57fDyKKTssdWGyx+fF2l+pbvvYIZyxEDoPNYUUV4NGq6mGZ8EfDe3BbjDhUZ2ivG7cGYEzwuQEzdAS9gKS+qKlBSBAdQ3LC+Km9bAWVMSribYwQzKgU+0n76BjyhEmFr2XMfU/OzMUfkXGnaDhWo9fglqi9y/FQ0rw2mcrSo3JbWcbrK9Gj/znTrCVcxnPgPrlwstN/MHJAm9+vdqSoVK0jp3D2MfqSLZ5+1PrdgVmK4PYjD8mCXwgLS06hYHltpjfUrtd7sdfk9rvLBSBUDVJwKwyg+aU9IoeeuAjAnri96Jw1AWqUQ4Aj7I1cyKiz2XmHmmeamZZrzabakzQmy97PKWDbtVDHJ0xajK+bsNQqoMKrC2neGSMlv9ZwLJBfhiNda85PEqKKJtxFhJPnwAojIpScYkuoUUNPHWFw/frCqiQXUa7GOIV7tGLWIB63LxEt7h59V2AgpvyfDHiGrFlGegJ+OLxS0tGxTovpIMxvASo1V0=
  on:
    branch: master
    repo: deblockt/hal-rest-client
  skip_cleanup: true
